trigger:
  branches:
    include:
      - main

extends:
  template: deploy.yml
  parameters:
    variables_group: 'admin-client-prod-variable-group'
    service_connection: 'prod-service-connection'
    static_web_app_name: 'prod-retornos-admin-client'
